pipeline {

    agent none

    stages {
        agent {
            docker {
               image 'python:2.7.16-slim'
                   args '--user root'
            }
          }
        stage('build') {
            when {
              changeset '**/vote/**'
            }
            steps {
                echo 'Compiling vote app'
                sh 'pip install -r requirements.txt'

            }
        }
         stage('test') {
             agent {
                docker {
                   image 'python:2.7.16-slim'
                       args '--user root'
                }
            }
            when {
              changeset '**/vote/**'
            }
            steps {
                echo 'Running unit tests on vote app'
                 sh 'pip install -r requirements.txt'
                 sh 'nosetests -v'
            }
        }

         stage('docker-package') {
            agent any
            when {
              changeset '**/vote/**'
            }
            steps {
              echo 'Packaging vote app with docker'
                script {
                docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                    def workerImage = docker.build("josenoriega/vote:v${env.BUILD_ID}", "./vote")
                    workerImage.push()
                    workerImage.push("${env.BRANCH_NAME}")
                }
              } 
            }
        }
    }
    
    
}
