version: '3.7'
volumes:
   db-data:

networks:
  instavote:
    driver: bridge

services:
 vote:
   image: josenoriega/vote:master
   build: ./vote
   ports:
     - 5000:80
   depends_on: 
     - redis
   networks: 
     - instavote


 result:
   image: josenoriega/result:master
   build: ./result
   ports:
     - 5001:4000
   depends_on:
     - db
   networks:
     - instavote

 worker:
   image: josenoriega/worker
   build: ./worker
   networks: 
     - instavote


 redis:
  image: redis:alpine
  networks: 
     - instavote

 db:
  image: postgres:9.4
  #volumes:
  #   - "db-data:/var/lib/postgresql/data"
  networks: 
     - instavote
  environment:
     - POSTGRES_HOST_AUTH_METHOD=trust